name: Build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

  push:
    branches:
    - main
    - dev
    - preview
    - v*

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          fetch-depth: 0

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
          dotnet-version: '8.0.x'

    - name: Add .NET Workloads
      run: dotnet workload install maui ios android

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build
      run: msbuild Shiny.Health/Shiny.Health.csproj -t:rebuild /restore -m -property:Configuration=Release -property:PublicRelease=true

    - name: Post NuGet Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nuget-artifacts
        path: '**/*.nupkg'

    - name: Publish NuGets
      if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/v') }}
      run: dotnet nuget push **\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGETAPIKEY }} --skip-duplicate